spring.application.name=AttendenceLeaveManagementSystem

spring.datasource.url=jdbc:postgresql://ep-snowy-wildflower-awbp0ifa-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VS9XR3PkjQJW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect